import { NextRequest, NextResponse } from "next/server";

/**
 * POST /api/recommend/llm-review
 *
 * Forwards a list of recommended components to the user's LLM (OpenAI or
 * Anthropic) for an expert review. The API key is provided by the user at
 * request time and is never stored.
 *
 * Body:
 *   {
 *     apiKey: string,
 *     provider: "openai" | "anthropic",
 *     model?: string,
 *     components: RecommendedComponent[],
 *     constraints: RecommendationConstraints,
 *     userPrompt?: string
 *   }
 */

interface LLMReviewRequest {
  apiKey: string;
  provider: "openai" | "anthropic";
  model?: string;
  components: Array<{
    title: string;
    type: string;
    category: string;
    subcategory: string;
    price: number | null;
    purchaseUrl: string;
    interfaces: string[];
    voltageRange: { min: number | null; max: number | null };
    score: number;
    matchReasons: string[];
    description: string;
  }>;
  constraints: Record<string, unknown>;
  userPrompt?: string;
}

function buildSystemPrompt(): string {
  return `You are an expert IoT/CPS hardware engineer and system architect. You have deep knowledge of microcontrollers, sensors, actuators, communication protocols, and power management for embedded systems.

You are reviewing a set of hardware component recommendations generated by the ARC-Twin recommender system. Your job is to:

1. **Evaluate the recommendations** — assess if the components are suitable for the user's constraints and use case.
2. **Flag compatibility issues** — identify potential voltage mismatches, interface incompatibilities, or other hardware conflicts between components.
3. **Suggest improvements** — recommend better alternatives, missing components (e.g., level shifters, pull-up resistors, decoupling capacitors), or design considerations.
4. **Rank your top picks** — from the recommended list, highlight the best 2–3 choices and explain why.
5. **Provide wiring/integration tips** — brief notes on how key components connect.

Be concise but thorough. Use technical language appropriate for an embedded systems audience.`;
}

function buildUserMessage(req: LLMReviewRequest): string {
  const constraintLines = Object.entries(req.constraints)
    .filter(([, v]) => v !== undefined && v !== null && v !== "")
    .map(([k, v]) => `  - ${k}: ${JSON.stringify(v)}`)
    .join("\n");

  const componentLines = req.components
    .slice(0, 15) // Limit to top 15 to stay within token limits
    .map((c, i) => {
      const voltage = c.voltageRange.min !== null
        ? `${c.voltageRange.min}V–${c.voltageRange.max ?? "?"}V`
        : "unknown";
      return `${i + 1}. **${c.title}**
   - Type: ${c.type} | Category: ${c.category}/${c.subcategory}
   - Price: ${c.price !== null ? `$${c.price.toFixed(2)} CAD` : "unknown"}
   - Interfaces: ${c.interfaces.length > 0 ? c.interfaces.join(", ") : "not specified"}
   - Voltage: ${voltage}
   - Match reasons: ${c.matchReasons.join("; ")}
   - Description: ${c.description.slice(0, 200)}`;
    })
    .join("\n\n");

  let prompt = `## User Constraints
${constraintLines || "  (no specific constraints)"}

## Recommended Components (${req.components.length} total, showing top ${Math.min(15, req.components.length)})

${componentLines}`;

  if (req.userPrompt) {
    prompt += `\n\n## Additional User Question\n${req.userPrompt}`;
  }

  return prompt;
}

async function callOpenAI(
  apiKey: string,
  model: string,
  systemPrompt: string,
  userMessage: string
): Promise<string> {
  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userMessage },
      ],
      temperature: 0.3,
      max_tokens: 2000,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`OpenAI API error ${response.status}: ${err}`);
  }

  const data = await response.json();
  return data.choices?.[0]?.message?.content ?? "No response generated.";
}

async function callAnthropic(
  apiKey: string,
  model: string,
  systemPrompt: string,
  userMessage: string
): Promise<string> {
  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model,
      max_tokens: 2000,
      system: systemPrompt,
      messages: [{ role: "user", content: userMessage }],
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Anthropic API error ${response.status}: ${err}`);
  }

  const data = await response.json();
  const content = data.content;
  if (Array.isArray(content)) {
    return content
      .filter((block: { type: string }) => block.type === "text")
      .map((block: { text: string }) => block.text)
      .join("\n");
  }
  return "No response generated.";
}

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as LLMReviewRequest;

    if (!body.apiKey || !body.provider) {
      return NextResponse.json(
        { error: "API key and provider are required." },
        { status: 400 }
      );
    }

    if (!body.components || body.components.length === 0) {
      return NextResponse.json(
        { error: "No components to review." },
        { status: 400 }
      );
    }

    const systemPrompt = buildSystemPrompt();
    const userMessage = buildUserMessage(body);

    let review: string;

    if (body.provider === "openai") {
      const model = body.model || "gpt-4o-mini";
      review = await callOpenAI(body.apiKey, model, systemPrompt, userMessage);
    } else if (body.provider === "anthropic") {
      const model = body.model || "claude-sonnet-4-20250514";
      review = await callAnthropic(body.apiKey, model, systemPrompt, userMessage);
    } else {
      return NextResponse.json(
        { error: `Unsupported provider: ${body.provider}` },
        { status: 400 }
      );
    }

    return NextResponse.json({ review });
  } catch (error) {
    console.error("LLM review error:", error);
    const message = error instanceof Error ? error.message : "LLM review failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
